### PR TITLE
Andrii/create account

### PR DESCRIPTION
**Pull request by Developik**
#4 

Added Create User logic on front-end
Added Create User logic on back-end

More tests will be added later

### CODE REVIEW

**Comment by Dankgen** [comment]
Looks good, just a few questions.
Was there any reason for adding first and last names to users?
and just a nitpick about the User model. Is there a reason for adding all their likes/comments/posts into the model?

**Comment by Developik** [comment]
> Looks good, just a few questions. Was there any reason for adding first and last names to users? and just a nitpick about the User model. Is there a reason for adding all their likes/comments/posts into the model?

Well I just wanted that for user creation, it made sense to me to add name to user object for sign up form.
But if we are talking from functional perspective, then no, I don't have any other reasons to have it there for now.

About other fields and whether they are required we can talk with Edden

**Comment by Dankgen** [comment]
Just looked at some other social media sites, they also do names. I wont block because of the arrays in user, considering that those can just be left empty regardless

**Review by Dankgen — APPROVED** [review]
💸

**Comment by Developik** [comment]
Thanks, I'm merging then

**Pull request merged**
